### PR TITLE
Make alloc/free operations thread safe

### PR DESCRIPTION
**Pull request by fjtrujy**
I have followed same implementation we did in PSP

### CODE REVIEW

**Review by uyjulian — APPROVED** [review]
lgtm

**Comment by rickgaiser** [comment]
How does this work?

I can see newlib already has a `__malloc_lock`:
https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/stdlib/mlock.c
If MALLOC_PROVIDED is not defined.
Is this defined somewhere? I was expecting it here:
https://github.com/ps2dev/ps2toolchain-ee/blob/main/scripts/003-newlib.sh#L49

How is that one disabled?
How is this one used?
Where is _internal_malloc_lock defined?

**Comment by fjtrujy** [comment]
> How does this work?
> 
> I can see newlib already has a `__malloc_lock`: https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/stdlib/mlock.c If MALLOC_PROVIDED is not defined. Is this defined somewhere? I was expecting it here: https://github.com/ps2dev/ps2toolchain-ee/blob/main/scripts/003-newlib.sh#L49
> 
> How is that one disabled? How is this one used? Where is _internal_malloc_lock defined?

If you take a look at the description here:
https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/stdlib/mlock.c#L17-L29

```
If multiple threads of execution can call <<malloc>>, or if <<malloc>> can be called reentrantly, then you need to define your own versions of these functions in order to safely lock the memory pool during a call.  If you do not, the memory pool may become corrupted.
```

So basically we need to define our own `void __malloc_lock (ptr)` and `void __malloc_unlock (ptr)`.
What I did was just create a dummy implementation of these functions on the `mlock.c` file which calls the `_internal_malloc_lock();` and `_internal_malloc_unlock();`.
These functions as the other "glue" functions are defined in the `ps2sdk/ee/libcglue` as you can see in the ps2sdk's PR:
https://github.com/ps2dev/ps2sdk/pull/430/files

This is exactly the same way that PSP does. Let me know if there is a better way.
https://github.com/pspdev/newlib/blob/allegrex-v4.1.0/newlib/libc/sys/psp/mlock.c
https://github.com/pspdev/pspsdk/blob/1cbba381ac42b77568a69450546233a850fec937/src/libcglue/glue.c#L804-L816

Cheers

**Comment by fjtrujy** [comment]
I forgot to reply about: `How is that one disabled?`
I'm not sure how newlib does, but I had the impression that either all the functions on newlib are somehow weak, or there is a compilation order that matters, compiling first the user-defined functions.

**Comment by rickgaiser** [comment]
So [newlib/libc/sys/ps2/mlock.c](https://github.com/ps2dev/newlib/pull/6/files#diff-9725779bfbbcfaf84eda06b9c26177a8c1e6f19e16dd0cb9b946077ca419784e) replaces [newlib/libc/stdlib/mlock.c](https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/stdlib/mlock.c) (in an unknown way).

Then the new functions call `_internal_malloc_(un)lock` from ps2sdk, instead of the newlib "lock API".
Wouldn't implementing the "lock API" fix all locking issues in newlib (instead of only fixing malloc) ?

> A call to <<malloc>> may call <<__malloc_lock>> recursively; that is,
> the sequence of calls may go <<__malloc_lock>>, <<__malloc_lock>>,
> <<__malloc_unlock>>, <<__malloc_unlock>>.  Any implementation of these
> routines must be careful to avoid causing a thread to wait for a lock
> that it already holds.
> 
I notice ps2sdk uses a single non recursive lock, so this can become an issue.

**Comment by fjtrujy** [comment]
> So [newlib/libc/sys/ps2/mlock.c](https://github.com/ps2dev/newlib/pull/6/files#diff-9725779bfbbcfaf84eda06b9c26177a8c1e6f19e16dd0cb9b946077ca419784e) replaces [newlib/libc/stdlib/mlock.c](https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/stdlib/mlock.c) (in an unknown way).
> 
> Then the new functions call `_internal_malloc_(un)lock` from ps2sdk, instead of the newlib "lock API". Wouldn't implementing the "lock API" fix all locking issues in newlib (instead of only fixing malloc) ?
> 
> > A call to <> may call <<__malloc_lock>> recursively; that is,
> > the sequence of calls may go <<__malloc_lock>>, <<__malloc_lock>>,
> > <<__malloc_unlock>>, <<__malloc_unlock>>.  Any implementation of these
> > routines must be careful to avoid causing a thread to wait for a lock
> > that it already holds.
> 
> I notice ps2sdk uses a single non recursive lock, so this can become an issue.

Yes, we should implement somehow the "Lock API" in `newlib` I just didn't find a proper way of doing this yet...
We can see how it was done in linux....
https://github.com/ps2dev/newlib/blob/ee-v4.1.0/newlib/libc/sys/linux/sys/lock.h

**Comment by fjtrujy** [comment]
Closing in favor of https://github.com/ps2dev/ps2toolchain-ee/pull/29

**Pull request closed without merging**
